apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      This template creates the credentials used by various
      components of this application.
    iconClass: icon-node
    tags: node
  name: mobile-signing-service-secrets
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: mobile-signing-service
      name: minio-creds
    stringData:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    type: Opaque
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: mobile-signing-service
      name: sso-creds
    stringData:
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
    type: Opaque
parameters:
  - name: MINIO_ACCESS_KEY
    displayName: The Minio access key
    from: '[a-zA-Z0-9]{12}'
    generate: expression
  - name: MINIO_SECRET_KEY
    displayName: The Minio secret key
    from: '[a-zA-Z0-9]{16}'
    generate: expression
  - name: SSO_CLIENT_SECRET
    description: The secret name of sso-credentials.
    displayName: SSO secret name
    required: true
