apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: devhub-signing-web-deployment
metadata:
  creationTimestamp: null
  name: devhub-signing-web-deployment
  namespace: devhub-tools
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}-caddy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}-caddy
      spec:
        containers:
        - args:
          - /tmp/scripts/run
          env:
          - name: SSO_BASE_URL
            value: ${SSO_BASE_URL_VALUE}
          image: ${NAME}-caddy@${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${NAME}-caddy
          ports:
          - containerPort: 2015
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/Caddyfile
            name: ${VOLUMN_NAME}
            readOnly: true
            subPath: Caddyfile
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: "420"
            name: ${NAME}-caddy
          name: ${VOLUMN_NAME}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}-caddy
        from:
          kind: ImageStreamTag
          name: ${NAME}-caddy:${IMAGE_TAG}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${ROUTE_NAME}
  spec:
    port:
      targetPort: 2015-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  data:
    Caddyfile: |-
      0.0.0.0:2015
      root /var/www/html
      log stdout
      errors stdout
      rewrite {
        if    {path} not_match ^\/0.0.0.0
        to    {path} {path}/ /?_url={uri}
      }
  kind: ConfigMap
  metadata:
    labels:
      app: ${NAME}-caddy
    name: ${NAME}-caddy
parameters:
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  required: true
  value: devhub-tools
- description: The name assigned to all of the objects defined in this template.  You
    should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: signing-web
- description: The suffix for all created objects
  displayName: Name
  name: IMAGE_TAG
  required: false
  value: latest
- description: The name of the default route use to access this service.
  displayName: Application Route
  name: ROUTE_NAME
  required: true
  value: signing-web
- description: The volumn name for caddyfile
  displayName: The volumn name for caddyfile
  name: VOLUMN_NAME
  required: true
  value: web-caddy-config
- description: The name assigned to all of the objects defined in this template.  You
    should keep this as default unless your know what your doing.
  displayName: Name
  name: API_SERVICE_NAME
  required: true
  value: signing-api
- description: ""
  displayName: Name
  name: SSO_BASE_URL_VALUE
  required: true
